spring:
  kafka:
    config:
      application-id: kafka-project
      bootstrap-servers: 93.180.177.75:9092
      inbox-topic: inbox-topic
      outbox-topic: outbox-topic
      group-id: group-id
      auto-offset: earliest