name: KafkaProject pipeline
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [ push ]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Execute test suite
        run: |
          cd ${{ github.workspace }}
          sudo apt install openjdk-17-jre
          sudo bash ./gradlew test -Dorg.gradle.java.home=/usr/lib/jvm/java-17-openjdk-amd64