name: KafkaProject pipeline
run-name: ${{ github.actor }} is running the pipeline
on: [ push ]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Install java jre
        run: |
          sudo apt install openjdk-17-jre
      - name: Execute test suite
        run: |
          ls -lah
#          sudo bash ./gradlew test -Dorg.gradle.java.home=/usr/lib/jvm/java-17-openjdk-amd64